baseURL = "https://www.plotbridge.io"
title = "PlotBridge"
theme = "coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Plot Network Ltd"
authorUrl = "https://plotnetwork.ltd"
description = "PlotBridge - a service from PlotNetwork"
keywords = "BSC,plotnetwork,plotbridge,defi,XCH,XCC,Chia,Chives,PXCC,PXCH"
info = ["DeFi gateway for Plot farmers", "Connects Chia and fork coins to BSC"]
avatarURL = "images/big-logo.svg"
homeBackground = "images/n90.jpg"
dateFormat = "January 2, 2021"
footNote = "Plot Network, Ltd is not affiliated with Chia Network, Inc. Chia™ may be a trademark or registered trademark of Chia Network, Inc. All third party trademarks are the property of their respective owners."
since = 2021
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 1
url = "https://twitter.com/plot_bridge"
target = "_blank"

[[params.social]]
name = "Discord"
icon = "fa fa-2x fa-discord"
weight = 2
url = "https://discord.com/invite/xHC9fBfeVW"
target = "_blank"


[[params.social]]
name = "Telegram"
icon = "fa fa-2x fa-telegram"
weight = 3
url = "https://t.me/plotbridge"
target = "_blank"


[[params.social]]
name = "Medium"
icon = "fa fa-2x fa-medium"
weight = 4
url = "https://medium.com/@plotbridge"
target = "_blank"


[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "App"
weight = 2
url = "https://app.plotbridge.net/"
target = "_blank"

[[languages.en.menu.main]]
name = "Guide"
weight = 3
url = "guide/"

[[languages.en.menu.main]]
name = "FAQ"
weight = 4
url = "faq/"


[[languages.en.menu.main]]
name = "Contact"
weight = 5
url = "contact/"


[languages.zh-cn]
languageName = ":cn:"

[languages.zh-cn.params]
info = "连接空间矿工和DeFi"
description = "PlotBridge 项目信息"
keywords = "plotbridge,桥,币安,智能链,奇亚,韭菜"

[[languages.zh-cn.menu.main]]
name = "关于"
weight = 1
url = "about/"

[[languages.zh-cn.menu.main]]
name = "指南"
weight = 3
url = "guide/"

[[languages.zh-cn.menu.main]]
name = "App"
weight = 2
url = "https://app.plotbridge.net/"

[[languages.zh-cn.menu.main]]
name = "常见问题"
weight = 4
url = "faq/"

[[languages.zh-cn.menu.main]]
name = "联系我们"
weight = 5
url = "contact/"


